<a href="https://colab.research.google.com/github/ZiChengHao/Mat-494/blob/main/homework2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 NumPy data structure

1.1 NumPy vector or 1-D array

In [ ]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.zeros(10)
b = np.ones(10)
c = np.zeros(10) + 5
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# use random numbers to populate an array
a = np.random.rand(10)
print(a)

[0.51901339 0.24373449 0.87568703 0.18238267 0.3570539  0.5536122
 0.6079988  0.12521309 0.78680925 0.90774738]


In [ ]:
# index
a = np.arange(10)
print(a)
print(a[-1])
print(a[1:3])
print(a[1:5:2])

[0 1 2 3 4 5 6 7 8 9]
9
[1 2]
[1 3]


1.2 Numpy Array


In [ ]:
a = np.zeros((3, 5))
# note the extra bracket you need for calling np.zeros
print(a, '\n')

# shape of the array
print('len =',len(a))
print('shape =',a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

len = 3
shape = (3, 5)


In [ ]:
a = np.zeros((3,5))
nx,ny = a.shape
print('nx =', nx)
print('ny =', ny)

nx = 3
ny = 5


In [ ]:
a = np.zeros((3,5)) + 7
print(a, '\n')

b = np.ones((3,5)) * 7
print(b, '\n')

c = np.full((3,5), 7)
print(c)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a = np.array(([1,2], [3,4], [5,6]))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[1, :]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')
print(a[[0,1,2],[2,1,2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 3  6 11]


In [ ]:
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[1,:] += 10
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [ 0.  1.  2.]]


In [ ]:
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[:,2] = 5.
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[0. 1. 5.]
 [0. 1. 5.]
 [0. 1. 5.]]


In [ ]:
a=np.array(([1,1],[1,1]))
print(a)
print(a.dtype)

[[1 1]
 [1 1]]
int64


In [ ]:
a=np.array(([1.,1],[1,1]))
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64


In [ ]:
a=np.array(([1.,1],[1,1]))>2
print(a)
print(a.dtype)

[[False False]
 [False False]]
bool


In [ ]:
a=np.array((['1','1'],['1','1']))
print(a)
print(a.dtype)

[['1' '1']
 ['1' '1']]
<U1


In [ ]:
a=np.array((['1','1'],['1','1']),dtype=float)
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64
