<a href="https://colab.research.google.com/github/ZiChengHao/Mat494/blob/main/homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 NumPy data structure

1.1 NumPy vector or 1-D array

In [1]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.zeros(10) + 5
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [3]:
# use random numbers to populate an array
a = np.random.rand(10)
print(a)

[0.28028347 0.2343934  0.12280436 0.17530863 0.15242225 0.85652116
 0.47926363 0.40798633 0.91891629 0.11478434]


In [4]:
# index
a = np.arange(10)
print(a)
print(a[-1])
print(a[1:3])
print(a[1:5:2])

[0 1 2 3 4 5 6 7 8 9]
9
[1 2]
[1 3]
